### ISSUE TITLE
时间日期可能会显示的太长,导致看不到全部

### ISSUE THREAD

**Issue by mnyon** [mcwz/showtime-siyuan#1]
![Image](https://github.com/user-attachments/assets/f550a2e1-6f4c-4422-985d-427a29278c81)
Hi! 感谢作者的辛勤付出,这个插件真的太棒了,有太多时候想知道笔记的记录时间,这帮了大忙,但是它的显示有一点点的小问题,因为我喜欢放大(Ctrl + 滚轮)了的UI,所以总是看不到合适时间大小,这有些繁琐要反复切换大小.但是瑕不掩瑜,感谢作者!

**Comment by zhao-heng-sheng** [comment]
可以在外观里面自定义css代码片段，目前我是改到了最右边
```css
[data-node-id][data-type='NodeParagraph']::after{
top:auto !important;
left:auto !important;
right:0;
}
```
